import logging
import os
from pathlib import Path
from typing import List, TypedDict
from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from fpdf import FPDF

# Import our existing isolated RAG agent
from agent import SecureDocAgent

logger = logging.getLogger(__name__)

# ==========================================
# 1. State & Data Models
# ==========================================
class MultiAgentState(TypedDict):
    target_contract: str
    research_query: str
    audit_framework: str
    extracted_clauses: List[str]
    compliance_gaps: List[str]
    risk_report: str
    status: str

class ComplianceCheck(BaseModel):
    is_compliant: bool = Field(description="True if the clause meets the framework rules, False otherwise.")
    violation_details: str = Field(description="Details of any violations, or 'None' if perfectly compliant.")
    suggested_amendment: str = Field(description="Exact suggested rewording to fix the contract, or 'None'.")

# ==========================================
# 2. PDF Generator Utility
# ==========================================
class AuditReportPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 15)
        self.set_text_color(41, 128, 185) # Professional Blue
        self.cell(0, 10, "Automated Compliance & Risk Audit", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Secure Doc-Intelligence Agent", align="C")

def sanitize_for_pdf(text: str) -> str:
    """Edge Case Handling: Strips complex Unicode/Emojis that crash standard PDF fonts."""
    if not text:
        return "No data provided."
    replacements = {
        '“': '"', '”': '"', '‘': "'", '’': "'", '–': '-', '—': '-',
        '…': '...', '✅': '[COMPLIANT]', '❌': '[VIOLATION]', '💡': '[SUGGESTION]',
        '*': '', '#' : '' # Strip markdown for clean PDF
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # Encode to latin-1 and ignore unmappable characters
    return text.encode('latin-1', 'ignore').decode('latin-1')

# ==========================================
# 3. The Multi-Agent Orchestrator
# ==========================================
class ComplianceOrchestrator:
    def __init__(self, db_dir: str):
        self.llm = ChatOpenAI(model="gpt-4o", temperature=0)
        self.doc_agent = SecureDocAgent(db_dir=db_dir)
        self.db_dir = db_dir

    def research_node(self, state: MultiAgentState):
        logger.info(f"MULTI-AGENT [Research]: Searching for '{state['research_query']}'")
        metadata_filter = {"source": state["target_contract"]} if state["target_contract"] != "All Documents" else None
        try:
            result = self.doc_agent.query(state["research_query"], metadata_filter=metadata_filter)
            extracted = result["answer"]
        except Exception as e:
            logger.error(f"Research Node failed: {e}")
            extracted = f"System Error extracting clauses: {str(e)}"
        return {"extracted_clauses": [extracted], "status": "Research Complete"}

    def auditor_node(self, state: MultiAgentState):
        logger.info("MULTI-AGENT [Auditor]: Running compliance checks...")
        auditor_llm = self.llm.with_structured_output(ComplianceCheck)
        prompt = (
            f"You are a strict legal auditor. Compare these extracted clauses:\n\n'{state['extracted_clauses'][0]}'\n\n"
            f"Against this mandatory framework:\n\n'{state['audit_framework']}'\n\n"
            f"Identify any gaps, missing obligations, or direct violations."
        )
        try:
            check = auditor_llm.invoke(prompt)
            if check.is_compliant:
                gap_report = "✅ Clause is fully compliant. No amendments needed."
            else:
                gap_report = f"❌ Violation Found: {check.violation_details}\n💡 Suggested Amendment: {check.suggested_amendment}"
        except Exception as e:
            logger.error(f"Auditor Node failed: {e}")
            gap_report = f"⚠️ Could not complete audit due to parsing error: {str(e)}"
        return {"compliance_gaps": [gap_report], "status": "Auditing Complete"}

    def analyst_node(self, state: MultiAgentState):
        logger.info("MULTI-AGENT [Analyst]: Drafting executive report...")
        prompt = (
            f"Based on the following compliance gaps found in '{state['target_contract']}':\n{state['compliance_gaps'][0]}\n\n"
            f"Write a professional, 3-paragraph executive risk assessment for a Managing Partner. "
            f"Be concise, authoritative, and highlight business risk."
        )
        try:
            report = self.llm.invoke(prompt)
            final_report = report.content
        except Exception as e:
            logger.error(f"Analyst Node failed: {e}")
            final_report = "System failed to generate final risk report."
        return {"risk_report": final_report, "status": "Finished"}

    def build_workflow(self):
        builder = StateGraph(MultiAgentState)
        builder.add_node("researcher", self.research_node)
        builder.add_node("auditor", self.auditor_node)
        builder.add_node("analyst", self.analyst_node)
        builder.set_entry_point("researcher")
        builder.add_edge("researcher", "auditor")
        builder.add_edge("auditor", "analyst")
        builder.add_edge("analyst", END)
        return builder.compile()

    def generate_pdf(self, state: dict, session_hash: str) -> str:
        """Generates a physical PDF report and saves it securely to the user's session folder."""
        logger.info("Generating PDF Report...")
        pdf = AuditReportPDF()
        pdf.add_page()
        
        # Target Document
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, f"Target Document: {sanitize_for_pdf(state['target_contract'])}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # 1. Extracted Clauses
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "1. Extracted Legal Clauses", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 6, sanitize_for_pdf(state['extracted_clauses'][0]))
        pdf.ln(5)

        # 2. Auditor Findings
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 10, "2. Auditor Findings & Gap Analysis", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 6, sanitize_for_pdf(state['compliance_gaps'][0]))
        pdf.ln(5)

        # 3. Executive Risk Assessment
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 10, "3. Executive Risk Assessment", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 6, sanitize_for_pdf(state['risk_report']))

        # Save to user's isolated directory
        output_dir = Path("user_sessions") / session_hash
        output_path = output_dir / "Compliance_Audit_Report.pdf"
        pdf.output(str(output_path))
        
        return str(output_path)

    def run_audit(self, target_contract: str, research_query: str, audit_framework: str, session_hash: str) -> tuple:
        """Runs the audit and returns (markdown_string, path_to_pdf)."""
        workflow = self.build_workflow()
        initial_state = {
            "target_contract": target_contract,
            "research_query": research_query,
            "audit_framework": audit_framework,
            "status": "Initializing..."
        }
        
        final_state = workflow.invoke(initial_state)
        
        # Generate the PDF
        pdf_path = self.generate_pdf(final_state, session_hash)
        
        return final_state, pdf_path