"""add subscriptions and credit_transactions tables

Revision ID: 1c78bcf7f9b5
Revises: ff009a3b6dec
Create Date: 2026-03-25 13:17:06.397343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c78bcf7f9b5'
down_revision: Union[str, Sequence[str], None] = 'ff009a3b6dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('credits_delta', sa.Integer(), nullable=False),
    sa.Column('credits_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_monthly_quota', sa.Integer(), nullable=False),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('advance_tax_computations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('advance_tax_computations', 'estimated_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advance_tax_computations', 'total_interest',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advance_tax_computations', 'interest_234a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advance_tax_computations', 'interest_234b',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advance_tax_computations', 'interest_234c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advance_tax_computations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('advance_tax_computations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bank_statement_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bank_statement_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'total_gain_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'total_estimated_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'ltcg_equity_taxable',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'stcg_equity_net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'exemption_112a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'reconciliation_warnings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('capital_gains_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint('uq_client_ca_user_name', 'clients', ['ca_user_id', 'name'])
    op.alter_column('depreciation_analyses', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('depreciation_analyses', 'total_assets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('depreciation_analyses', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'it_act_depreciation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'ca_depreciation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'timing_difference',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'deferred_tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depreciation_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('depreciation_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('gst_reconciliations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('gst_reconciliations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('gstr9_reconciliations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('gstr9_reconciliations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gstr9_reconciliations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('gstr9_reconciliations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('gst_reconciliations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('gst_reconciliations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('depreciation_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('depreciation_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('depreciation_analyses', 'deferred_tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depreciation_analyses', 'timing_difference',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depreciation_analyses', 'ca_depreciation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depreciation_analyses', 'it_act_depreciation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depreciation_analyses', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depreciation_analyses', 'total_assets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('depreciation_analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('depreciation_analyses', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('uq_client_ca_user_name', 'clients', type_='unique')
    op.alter_column('capital_gains_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'reconciliation_warnings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'exemption_112a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'stcg_equity_net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'ltcg_equity_taxable',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'total_estimated_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'total_gain_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('capital_gains_analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bank_statement_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('bank_statement_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('advance_tax_computations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('advance_tax_computations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('advance_tax_computations', 'interest_234c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advance_tax_computations', 'interest_234b',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advance_tax_computations', 'interest_234a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advance_tax_computations', 'total_interest',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advance_tax_computations', 'estimated_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advance_tax_computations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('subscriptions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
