"""add_gst_recon_itc_cess_fields

Revision ID: 62e7bd60d489
Revises: de9f453f5da8
Create Date: 2026-04-06 17:51:01.185068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e7bd60d489'
down_revision: Union[str, Sequence[str], None] = 'de9f453f5da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gst_reconciliations', sa.Column('total_itc_ineligible', sa.Float(), server_default='0', nullable=False))
    op.add_column('gst_reconciliations', sa.Column('total_cess', sa.Float(), server_default='0', nullable=False))
    op.add_column('gst_reconciliations', sa.Column('duplicate_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gst_reconciliations', 'duplicate_count')
    op.drop_column('gst_reconciliations', 'total_cess')
    op.drop_column('gst_reconciliations', 'total_itc_ineligible')
    # ### end Alembic commands ###
