"""Accuracy evaluation harness for the Bank Statement Analyzer.

Runs the end-to-end pipeline against known fixtures and verifies that the
expected flags fire, monthly totals match, and the new detectors behave
correctly on hand-crafted inputs. Exits non-zero on regression so this
script can be wired into CI.

Usage:
    python scripts/evaluate_bank_analyzer.py

Fixtures:
    1. test_bank_statement.pdf — real PDF generated by create_test_bank_statement.py
       (31 transactions designed to trigger 9 different flag types).
    2. In-memory transaction lists for isolated detector checks:
       - STRUCTURING_SUSPECTED (3x cash withdrawals 9K-9.99K same day)
       - ROUND_TRIP_SUSPECTED  (same counterparty debit↔credit within 7d)
       - HIGH_VALUE_NON_WORKING_DAY (>1L on Sunday / holiday)
       - MONTHLY_SPIKE (debit > 2× trailing 3-month avg)
"""

from __future__ import annotations

import os
import sys
from datetime import date
from pathlib import Path

# Allow running as `python scripts/evaluate_bank_analyzer.py` from repo root
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
os.chdir(REPO_ROOT)

import pymupdf  # PyMuPDF

from services.bank_statement_service import BankStatementService

PDF_FIXTURE = REPO_ROOT / "test_bank_statement.pdf"

# ---------------------------------------------------------------------------
# Expected ground truth for test_bank_statement.pdf
# ---------------------------------------------------------------------------
# Flag categories that MUST appear at least N times (N = min count).
# Derived from create_test_bank_statement.py comments and manual trace.
EXPECTED_FLAGS: dict[str, int] = {
    "SEC_269ST_VIOLATION": 4,       # 4 cash credits >= 2L
    "SEC_269ST_WARNING": 2,         # 2 cash credits in 1L-2L
    "SFT_CASH_DEPOSIT": 1,          # FY cash deposits ~15.2L >= 10L
    "INTEREST_194A_THRESHOLD": 1,   # Interest 80.5K > 40K
    "SEC_40A3_RISK": 1,             # Cash payment >10K
    "ROUND_AMOUNT_OBSERVATION": 1,  # At least one round-amount txn
    "SUNDAY_TRANSACTION": 1,        # 29-Jun-2025
}

# Minimum number of transactions parsed from the PDF
MIN_TRANSACTIONS = 25

# Compliance score should drop below 60 given the high number of HIGH flags
MAX_COMPLIANCE_SCORE = 60


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

class EvalResult:
    def __init__(self) -> None:
        self.passed: list[str] = []
        self.failed: list[str] = []

    def check(self, name: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed.append(name)
            print(f"  [OK]   {name}")
        else:
            msg = f"{name}" + (f" — {detail}" if detail else "")
            self.failed.append(msg)
            print(f"  [FAIL] {msg}")

    def summary(self) -> int:
        total = len(self.passed) + len(self.failed)
        print()
        print(f"Passed: {len(self.passed)}/{total}")
        if self.failed:
            print("Failures:")
            for f in self.failed:
                print(f"  - {f}")
            return 1
        print("All checks passed.")
        return 0


def _extract_pdf_text(pdf_path: Path) -> str:
    doc = pymupdf.open(str(pdf_path))
    try:
        return "\n".join(page.get_text() for page in doc)
    finally:
        doc.close()


# ---------------------------------------------------------------------------
# Test 1: real PDF end-to-end
# ---------------------------------------------------------------------------

def test_real_pdf(result: EvalResult) -> None:
    print("\n[1] End-to-end: test_bank_statement.pdf")

    if not PDF_FIXTURE.exists():
        print("  Fixture missing — run `python create_test_bank_statement.py` first.")
        result.check("PDF fixture present", False, f"{PDF_FIXTURE} not found")
        return

    svc = BankStatementService()
    raw_text = _extract_pdf_text(PDF_FIXTURE)
    transactions = svc.extract_transactions(raw_text)

    result.check(
        f"Parsed >= {MIN_TRANSACTIONS} transactions",
        len(transactions) >= MIN_TRANSACTIONS,
        f"got {len(transactions)}",
    )
    if not transactions:
        return

    analysis = svc.analyze(
        transactions,
        fy_start=date(2025, 4, 1),
        fy_end=date(2026, 3, 31),
    )

    # Count flag categories
    flag_counts: dict[str, int] = {}
    for f in analysis["flags"]:
        cat = f["category"]
        flag_counts[cat] = flag_counts.get(cat, 0) + 1

    for category, min_count in EXPECTED_FLAGS.items():
        actual = flag_counts.get(category, 0)
        result.check(
            f"Flag {category} fired >= {min_count}x",
            actual >= min_count,
            f"got {actual}",
        )

    # Enrichment output shape
    result.check(
        "monthly_summary is non-empty dict",
        isinstance(analysis.get("monthly_summary"), dict) and len(analysis["monthly_summary"]) > 0,
    )
    result.check(
        "categorized_totals is non-empty dict",
        isinstance(analysis.get("categorized_totals"), dict) and len(analysis["categorized_totals"]) > 0,
    )
    result.check(
        "counterparty_summary is list",
        isinstance(analysis.get("counterparty_summary"), list),
    )
    result.check(
        "compliance_score is integer 0-100",
        isinstance(analysis.get("compliance_score"), int)
        and 0 <= analysis["compliance_score"] <= 100,
    )
    result.check(
        f"compliance_score <= {MAX_COMPLIANCE_SCORE} given flag load",
        analysis["compliance_score"] <= MAX_COMPLIANCE_SCORE,
        f"got {analysis['compliance_score']}",
    )

    # Every transaction should carry category + counterparty after enrichment
    missing_cat = [t for t in transactions if not t.get("category")]
    result.check(
        "All transactions carry category",
        not missing_cat,
        f"{len(missing_cat)} without category",
    )
    missing_cp = [t for t in transactions if not t.get("counterparty")]
    result.check(
        "All transactions carry counterparty",
        not missing_cp,
        f"{len(missing_cp)} without counterparty",
    )

    # Monthly totals sanity: sum across months should match overall totals (within 1 rupee)
    sum_debit = sum(m["debit"] for m in analysis["monthly_summary"].values())
    sum_credit = sum(m["credit"] for m in analysis["monthly_summary"].values())
    result.check(
        "monthly_summary debit total matches summary",
        abs(sum_debit - analysis["summary"]["total_debit"]) < 1.0,
        f"monthly={sum_debit:.2f} summary={analysis['summary']['total_debit']:.2f}",
    )
    result.check(
        "monthly_summary credit total matches summary",
        abs(sum_credit - analysis["summary"]["total_credit"]) < 1.0,
        f"monthly={sum_credit:.2f} summary={analysis['summary']['total_credit']:.2f}",
    )


# ---------------------------------------------------------------------------
# Test 2: STRUCTURING_SUSPECTED
# ---------------------------------------------------------------------------

def test_structuring(result: EvalResult) -> None:
    print("\n[2] Detector: STRUCTURING_SUSPECTED")

    svc = BankStatementService()
    txns = [
        {"date": "2025-05-12", "description": "ATM CASH WDL BR1", "debit": "9500.00", "credit": "0", "mode": "ATM", "balance": "50000"},
        {"date": "2025-05-12", "description": "ATM CASH WDL BR2", "debit": "9800.00", "credit": "0", "mode": "ATM", "balance": "40000"},
        {"date": "2025-05-12", "description": "ATM CASH WDL BR3", "debit": "9900.00", "credit": "0", "mode": "ATM", "balance": "30000"},
        {"date": "2025-05-20", "description": "NEFT-CUSTOMER-INV1", "debit": "0", "credit": "100000.00", "mode": "NEFT", "balance": "130000"},
    ]
    analysis = svc.analyze(txns, fy_start=date(2025, 4, 1), fy_end=date(2026, 3, 31))
    fired = any(f["category"] == "STRUCTURING_SUSPECTED" for f in analysis["flags"])
    result.check("STRUCTURING_SUSPECTED fires on 3× cash 9K-9.99K same day", fired)


# ---------------------------------------------------------------------------
# Test 3: ROUND_TRIP_SUSPECTED
# ---------------------------------------------------------------------------

def test_round_trip(result: EvalResult) -> None:
    print("\n[3] Detector: ROUND_TRIP_SUSPECTED")

    svc = BankStatementService()
    txns = [
        {"date": "2025-06-02", "description": "NEFT-HDFC0000123-ACME TRADERS-INV1",
         "debit": "250000.00", "credit": "0", "mode": "NEFT", "balance": "200000"},
        {"date": "2025-06-05", "description": "NEFT-HDFC0000123-ACME TRADERS-REFUND",
         "debit": "0", "credit": "249000.00", "mode": "NEFT", "balance": "449000"},
    ]
    analysis = svc.analyze(txns, fy_start=date(2025, 4, 1), fy_end=date(2026, 3, 31))
    fired = any(f["category"] == "ROUND_TRIP_SUSPECTED" for f in analysis["flags"])
    result.check("ROUND_TRIP_SUSPECTED fires on same counterparty debit+credit within 7d", fired)


# ---------------------------------------------------------------------------
# Test 4: HIGH_VALUE_NON_WORKING_DAY
# ---------------------------------------------------------------------------

def test_non_working_day(result: EvalResult) -> None:
    print("\n[4] Detector: HIGH_VALUE_NON_WORKING_DAY")

    svc = BankStatementService()
    # 2025-10-02 is Gandhi Jayanti (hardcoded holiday)
    txns = [
        {"date": "02/10/2025", "description": "NEFT-N999-HOLIDAY TXN",
         "debit": "150000.00", "credit": "0", "mode": "NEFT", "balance": "500000"},
    ]
    analysis = svc.analyze(txns, fy_start=date(2025, 4, 1), fy_end=date(2026, 3, 31))
    fired = any(f["category"] == "HIGH_VALUE_NON_WORKING_DAY" for f in analysis["flags"])
    result.check("HIGH_VALUE_NON_WORKING_DAY fires on 1.5L NEFT on Gandhi Jayanti", fired)


# ---------------------------------------------------------------------------
# Test 5: MONTHLY_SPIKE
# ---------------------------------------------------------------------------

def test_monthly_spike(result: EvalResult) -> None:
    print("\n[5] Detector: MONTHLY_SPIKE")

    svc = BankStatementService()
    # 3 baseline months at ~50K debit, then a 300K debit month
    txns = []
    for day, month in [(10, 4), (15, 5), (20, 6)]:
        txns.append({
            "date": f"2025-{month:02d}-{day:02d}",
            "description": "NEFT-N000-VENDOR",
            "debit": "50000.00", "credit": "0", "mode": "NEFT", "balance": "100000",
        })
    txns.append({
        "date": "2025-07-15",
        "description": "NEFT-N001-LARGE VENDOR",
        "debit": "300000.00", "credit": "0", "mode": "NEFT", "balance": "50000",
    })
    analysis = svc.analyze(txns, fy_start=date(2025, 4, 1), fy_end=date(2026, 3, 31))
    fired = any(f["category"] == "MONTHLY_SPIKE" for f in analysis["flags"])
    result.check("MONTHLY_SPIKE fires when month debit > 2x trailing 3-month avg", fired)


# ---------------------------------------------------------------------------
# Test 6: Categorizer + counterparty on canonical narrations
# ---------------------------------------------------------------------------

def test_categorizer_and_counterparty(result: EvalResult) -> None:
    print("\n[6] Enrichment: categorizer + counterparty extraction")

    from services.bank_enrichment import categorize, extract_counterparty

    cases = [
        ("NEFT-SBIN0001234-RAJESH KUMAR SALARY", 75000.0, True, "SALARY", "NEFT", "RAJESH KUMAR SALARY"),
        ("UPI-123456-SWIGGY-PYTM", 450.0, False, "PERSONAL_EXPENSE", "UPI", None),
        ("NACH-HDFCLOAN-EMI-HOMELOAN", 52000.0, False, "EMI_LOAN_REPAYMENT", "NACH", None),
        ("GST PAYMENT CHALLAN CPIN12345", 32000.0, False, "GST_PAYMENT", None, None),
    ]
    for desc, amt, is_credit, expected_cat, expected_cp_type, expected_cp_name in cases:
        cat, _ = categorize(desc, amt, is_credit)
        cp = extract_counterparty(desc)
        result.check(
            f"categorize({desc[:40]!r}) -&gt; {expected_cat}",
            cat == expected_cat,
            f"got {cat}",
        )
        if expected_cp_type:
            result.check(
                f"counterparty type for {desc[:40]!r} == {expected_cp_type}",
                cp.get("type") == expected_cp_type,
                f"got {cp.get('type')}",
            )
        if expected_cp_name:
            result.check(
                f"counterparty name for {desc[:40]!r} contains {expected_cp_name!r}",
                expected_cp_name in (cp.get("name") or ""),
                f"got {cp.get('name')}",
            )


# ---------------------------------------------------------------------------
# Test 7: Holiday detection
# ---------------------------------------------------------------------------

def test_holidays(result: EvalResult) -> None:
    print("\n[7] Holiday detection")

    from services.bank_enrichment.holidays import is_bank_holiday, is_non_working_day

    result.check("2025-10-02 (Gandhi Jayanti) is a bank holiday", is_bank_holiday(date(2025, 10, 2)))
    result.check("2025-06-29 (Sunday) is non-working", is_non_working_day(date(2025, 6, 29)))
    result.check("2025-06-14 (2nd Saturday) is non-working", is_non_working_day(date(2025, 6, 14)))
    result.check("2025-06-16 (Mon) is working", not is_non_working_day(date(2025, 6, 16)))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    print("=" * 70)
    print("Bank Statement Analyzer — Accuracy Evaluation")
    print("=" * 70)

    result = EvalResult()
    test_real_pdf(result)
    test_structuring(result)
    test_round_trip(result)
    test_non_working_day(result)
    test_monthly_spike(result)
    test_categorizer_and_counterparty(result)
    test_holidays(result)

    print()
    print("=" * 70)
    return result.summary()


if __name__ == "__main__":
    sys.exit(main())
